# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer1.org1.example.com:
  peer0.org2.example.com:
  peer1.org2.example.com:

services:
#   appcli:
#     container_name: appcli
#     image: hyperledger/fabric-tools:latest
#     tty: true
#     stdin_open: true
# #    environment:
# #     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_byfn
# #      - GOPATH=/opt/gopath
# #      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
# #      - FABRIC_LOGGING_SPEC=DEBUG
# #      - FABRIC_LOGGING_SPEC=INFO
# #      - CORE_PEER_ID=appcli
# #      - CA_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem
# #      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
# #      - CORE_PEER_LOCALMSPID=Org1MSP
# #      - CORE_PEER_TLS_ENABLED=true
# #      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
# #      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
# #      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
# #      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
#     working_dir: /opt/
#     command: ./fccserver
#     volumes:
# #        - /var/run/:/host/var/run/
# #        - /opt/go/:/opt/go/
#         - ./fcc-server/fccserver:/opt/fccserver
#         - ./fcc-server/config.yaml:/opt/config.yaml
#         - ../first-network/crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#         - ../chaincode/:/opt/gopath/src/github.com/chaincode
#         - ../first-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
#     ports:
#       - 1206:1206


#     networks:
#       - example.com

  appcli:
    container_name: appcli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=appcli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/
    command: ./fccserver
    volumes:
        - ./fcc-server/fccserver:/opt/fccserver
        - ./fcc-server/config.yaml:/opt/config.yaml
        - ../first-network/crypto-config/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ../first-network/channel-artifacts/:/opt
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../first-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    ports:
      - 1206:1206
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com
      - peer1.org1.example.com
      - peer0.org2.example.com
      - peer1.org2.example.com
    networks:
      - byfn
